language: ruby
rvm:
  - jruby
  - rbx-2.1.1
  - 2.0.0
  - 2.1.1
  - 2.2.1
script: bundle exec rspec spec
before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - sudo apt-get -qq install gcc-4.9 libjansson-dev valgrind
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 90
  - wget https://github.com/PJK/libcbor/archive/master.zip
  - unzip master.zip
  - cd libcbor-master
  - git submodule update test/cmocka
  - cd test
  - mkdir cmocka_build && cd cmocka_build
  - cmake ../cmocka
  - make -j 4
  - sudo make install
  - cd ..
  - cmake .
  - sudo make install
  - cd ..