language: ruby
sudo: true
rvm:
  - 2.0.0
  - 2.1.1
  - 2.2.1
  - 2.3
  - 2.4
  - 2.5
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.6
    - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
    packages:
    - clang-3.6
    - libjansson-dev
    - valgrind
    - cppcheck
    - lcov
    - cmake
    - cmake-data
env: CC="clang-3.6" CXX="clang++-3.6"
script: bundle exec rspec spec
before_install:
  - pushd $HOME
  - git clone git://git.cryptomilk.org/projects/cmocka.git
  - mkdir cmocka_build
  - pushd cmocka_build
  - cmake ../cmocka
  - make -j 4
  - sudo make install
  - popd
  - rm -rf cmocka cmocka_build
  - git clone https://github.com/PJK/libcbor
  - pushd libcbor
  - cmake .
  - make VERBOSE=1
  - sudo make install
  - popd
  - popd
