language: ruby
rvm:
  - jruby
  - rbx-2.1.1
  - 2.0.0
  - 2.1.1
  - 2.2.1
script: bundle exec rspec spec
before_install:
  - wget https://github.com/PJK/libcbor/archive/master.zip
  - unzip master.zip
  - cd libcbor-master
  - cmake .
  - make cbor cbor_shared
  - sudo make install
  - cd ..